# Generated by Django 4.2.1 on 2023-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objetos_espaciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_lancamento', models.DateField()),
                ('veiculo_lancador', models.CharField(max_length=100)),
                ('cospar_id', models.CharField(max_length=100)),
                ('funcao_generica', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
